### ISSUE TITLE
show sold out message when sold out

### ISSUE THREAD

**Issue by lambtron** [denoland/merch#28]
![image](https://user-images.githubusercontent.com/1080190/188992538-916103ae-eb53-4e1e-9736-158afc3cd404.png)

right now, it just removes the "add to cart" button when sold out

**Comment by cjihrig** [comment]
It shows Out of Stock too:

<img width="491" alt="Screen Shot 2022-09-07 at 6 13 23 PM" src="https://user-images.githubusercontent.com/2512748/188992898-30122d50-73f8-44ce-b0ce-1e1ee3b23fa7.png">
