### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by rista404** [denoland/merch#31]
The website is currently not working, I'm getting 500 errors on all javascript files. Checked on my phone and other browsers as well.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/8061997/203612946-bad50a4b-e906-414f-bfbf-b957f3e107e0.png">

**Comment by robcodehub** [comment]
The site is not working for me either, I'm seeing similar errors as above and can't add any products to my cart.
